### ISSUE TITLE
Museum Subscribers can create foyer with wings from artist galleries

### ISSUE THREAD

**Issue by mscherotter** [mscherotter/galeryst#61]
** Tasks
- [x] Add Museum Gallery Creation UI
- [x] Add Museum Gallery Update UI
- [x] Add way for parent account to associate child accounts
- [ ] Add way for child account to associate parent account
- [x] Add help page
- [ ] Insure that browse page works
- [ ] Insure that accessible browse pages works
- [ ] Insure that gallery navigation works
